name: PumpkinDiver
main: com.afforess.pumpkindiver.PumpkinDiver
version: 0.2.0
author: Afforess
description: Pumpkin Diver allows deep-sea diving through a sophisticated pumpkin breathing apparatus.